[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true
  conditions = {Role = ["writer"]}

[[redirects]]
  from = "/admin/*"
  to = "/login/"
  status = 302
  force = true
